import { Room } from "../Types/types.tsx";

export const rooms = [
  {
    id: 1,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+1",
    type: "Luxury Villa",
    price: 2264000,
    address: "18 New Street, Miami, OR 97219",
    bedrooms: 8,
    bathrooms: 8,
    area: "545m²",
    floor: 3,
    parkingSpots: 6,
  },
  {
    id: 2,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+2",
    type: "Modern Apartment",
    price: 1180000,
    address: "54 Mid Street, Florida, OR 27001",
    bedrooms: 6,
    bathrooms: 5,
    area: "450m²",
    floor: 3,
    parkingSpots: 8,
  },
  {
    id: 3,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+3",
    type: "Luxury Villa",
    price: 1460000,
    address: "26 Old Street, Miami, OR 38540",
    bedrooms: 5,
    bathrooms: 2,
    area: "225m²",
    floor: 3,
    parkingSpots: 10,
  },
  {
    id: 4,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+4",
    type: "Beachfront House",
    price: 3500000,
    address: "12 Ocean Drive, Malibu, CA 90265",
    bedrooms: 7,
    bathrooms: 6,
    area: "600m²",
    floor: 2,
    parkingSpots: 4,
  },
  {
    id: 5,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+5",
    type: "Mountain Cabin",
    price: 980000,
    address: "34 Pine Ridge, Aspen, CO 81611",
    bedrooms: 4,
    bathrooms: 3,
    area: "350m²",
    floor: 1,
    parkingSpots: 2,
  },
  {
    id: 6,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+6",
    type: "Luxury Penthouse",
    price: 4200000,
    address: "78 Skyline Avenue, New York, NY 10001",
    bedrooms: 5,
    bathrooms: 4,
    area: "480m²",
    floor: 20,
    parkingSpots: 3,
  },
  {
    id: 7,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+7",
    type: "Rustic Farmhouse",
    price: 1200000,
    address: "90 Country Lane, Nashville, TN 37211",
    bedrooms: 6,
    bathrooms: 4,
    area: "500m²",
    floor: 2,
    parkingSpots: 5,
  },
  {
    id: 8,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+8",
    type: "Urban Loft",
    price: 1600000,
    address: "45 City Center, Chicago, IL 60601",
    bedrooms: 3,
    bathrooms: 2,
    area: "200m²",
    floor: 5,
    parkingSpots: 1,
  },
  {
    id: 9,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+9",
    type: "Lakefront Cottage",
    price: 850000,
    address: "15 Lakeview Drive, Seattle, WA 98101",
    bedrooms: 3,
    bathrooms: 2,
    area: "250m²",
    floor: 1,
    parkingSpots: 2,
  },
  {
    id: 10,
    imageUrl: "https://via.placeholder.com/400x300?text=Room+10",
    type: "Executive Suite",
    price: 2800000,
    address: "60 Central Park West, New York, NY 10023",
    bedrooms: 4,
    bathrooms: 3,
    area: "300m²",
    floor: 15,
    parkingSpots: 2,
  },
  {
    id: 1,
    imageUrl: "https://via.placeholder.com/600x400?text=Property+1",
    type: "Apartment",
    price: 500000,
    address: "24 New Street, Miami, FL 33101",
    bedrooms: 3,
    bathrooms: 2,
    area: "Downtown Miami",
    floor: 5,
    parkingSpots: 1,
    totalSpace: "1200 sq ft",
    contractStatus: "Contract Ready",
    paymentProcess: "Online Payment Available",
    safetyFeature: "24/7 Security System",
  }
];

export const property: Room = {
  id: 1,
  imageUrl: "https://via.placeholder.com/600x400?text=Property+1",
  type: "Apartment",
  price: 500000, // Added price field
  address: "24 New Street, Miami, FL 33101",
  bedrooms: 3, // Added bedrooms field
  bathrooms: 2, // Added bathrooms field
  area: "Downtown Miami", // Added area field
  floor: 5, // Added floor field
  parkingSpots: 1, // Added parkingSpots field
  totalSpace: "1200 sq ft",
  contractStatus: "Contract Ready",
  paymentProcess: "Online Payment Available",
  safetyFeature: "24/7 Security System",
};
